### ISSUE TITLE
org.openqa.selenium.net.HostIdentifier resolveHostName

### ISSUE THREAD

**Issue by kazurayam** [kazurayam/VisualInspectionOfCssAndJs#4]
v0.3.0-SNAPSHOT, when I exected Test Cases/MyAmdin with
Selenium 4`

``
`
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:460)
	at java.util.concurrent.TimeUnit.timedWait(TimeUnit.java:348)
	at java.lang.UNIXProcess.waitFor(UNIXProcess.java:410)
	at org.openqa.selenium.net.HostIdentifier.resolveHostName(HostIdentifier.java:52)
	at org.openqa.selenium.net.HostIdentifier.getHostName(HostIdentifier.java:116)
	at org.openqa.selenium.WebDriverException.getSystemInformation(WebDriverException.java:95)
	at org.openqa.selenium.WebDriverException.createMessage(WebDriverException.java:87)
	at org.openqa.selenium.WebDriverException.getMessage(WebDriverException.java:65)
	at java.lang.Throwable.getLocalizedMessage(Throwable.java:392)
	at java.lang.Throwable.toString(Throwable.java:481)
	at java.lang.Throwable.<init>(Throwable.java:312)
	at java.lang.Exception.<init>(Exception.java:102)
	at java.lang.RuntimeException.<init>(RuntimeException.java:96)
	at java.util.concurrent.CompletionException.<init>(CompletionException.java:88)
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Exception in thread "Driver Command Executor" java.lang.RuntimeException: java.lang.InterruptedException
	at org.openqa.selenium.net.HostIdentifier.resolveHostName(HostIdentifier.java:67)
	at org.openqa.selenium.net.HostIdentifier.getHostName(HostIdentifier.java:116)
	at org.openqa.selenium.WebDriverException.getSystemInformation(WebDriverException.java:95)
	at org.openqa.selenium.WebDriverException.createMessage(WebDriverException.java:87)
	at org.openqa.selenium.WebDriverException.getMessage(WebDriverException.java:65)
	at java.lang.Throwable.getLocalizedMessage(Throwable.java:392)
	at java.lang.Throwable.toString(Throwable.java:481)
	at java.lang.Throwable.<init>(Throwable.java:312)
	at java.lang.Exception.<init>(Exception.java:102)
	at java.lang.RuntimeException.<init>(RuntimeException.java:96)
	at java.util.concurrent.CompletionException.<init>(CompletionException.java:88)
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:460)
	at java.util.concurrent.TimeUnit.timedWait(TimeUnit.java:348)
	at java.lang.UNIXProcess.waitFor(UNIXProcess.java:410)
	at org.openqa.selenium.net.HostIdentifier.resolveHostName(HostIdentifier.java:52)
	... 16 more
1 25, 2022 12:28:00 午後 org.openqa.selenium.net.HostIdentifier resolveHostName
警告: Failed to resolve host name
```
https://giters.com/SeleniumHQ/selenium/issues/10111

**Comment by kazurayam** [comment]
This error was discussed

https://giters.com/SeleniumHQ/selenium/issues/10111

**Comment by kazurayam** [comment]
I want to cache the InterruptedException and hide it. How?

**Comment by kazurayam** [comment]
No. I can not catch RuntimeException.
